/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      keyframes: {
        "pulse-bg": {
          "0%, 100%": {
            "background-color": "#e5e5e5",
          },
          "50%": {
            "background-color": "#f5f5f5",
          },
        },
      },
      animation: {
        "pulse-bg": "pulse-bg 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
      backgroundImage: ({ theme }) => ({
        header: `linear-gradient(to bottom, 
          ${theme("colors.neutral.50/1")} 0%, 
          ${theme("colors.neutral.50/0.95")} 10%, 
          ${theme("colors.neutral.50/0.8")} 25%, 
          ${theme("colors.neutral.50/0.5")} 50%, 
          ${theme("colors.neutral.50/0.2")} 75%, 
          ${theme("colors.transparent")} 100%)`,
      }),
      fontFamily: {
        "satoshi-light": ["Satoshi-Light"],
        "satoshi-regular": ["Satoshi-Regular"],
        "satoshi-medium": ["Satoshi-Medium"],
        "satoshi-bold": ["Satoshi-Bold"],
        "satoshi-black": ["Satoshi-Black"],
      },
      height: {
        "5v": "5svh",
        "10v": "10svh",
        "15v": "15svh",
        "20v": "20svh",
        "30v": "30svh",
        "35v": "35svh",
        "40v": "40svh",
        "50v": "50svh",
        "60v": "60svh",
        "70v": "70svh",
        "80v": "80svh",
        "90v": "90svh",
        "100v": "100svh",
      },
      maxWidth: {
        "5v": "5svw",
        "10v": "10svw",
        "15v": "15svw",
        "20v": "20svw",
        "30v": "30svw",
        "35v": "35svw",
        "40v": "40svw",
        "50v": "50svw",
        "60v": "60svw",
        "70v": "70svw",
        "80v": "80svw",
        "90v": "90svw",
        "100v": "100svw",
        100: "100rem",
      },
      maxHeight: {
        80: "80rem",
      },
      minHeight: {
        50: "50rem",
      },
      spacing: {
        "5v": "5svh",
        "10v": "10svh",
        "15v": "15svh",
        "20v": "20svh",
        "30v": "30svh",
        "35v": "35svh",
        "40v": "40svh",
        "50v": "50svh",
        "60v": "60svh",
        "70v": "70svh",
        "80v": "80svh",
        "90v": "90svh",
        "100v": "100svh",
      },
    },
  },
  plugins: [require("tailwindcss-animated")],
};
