name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker registry
      run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin ${{ secrets.REGISTRY_URL }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.REGISTRY_URL }}/qnton:latest -f docker/Dockerfile .

    - name: Push Docker image
      run: docker push ${{ secrets.REGISTRY_URL }}/qnton:latest
